name: UltraTV-Dynamic-Streamer

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: 'رابط القرآن أو المباراة'
        required: true
        default: 'http://ibo.lynxiptv.com/334188914694/VzDd0nBIgq/66384'

jobs:
  streaming_job:
    runs-on: ubuntu-latest
    steps:
      - name: Update System & Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg ca-certificates
          sudo update-ca-certificates

      - name: Start Robust Stream
        run: |
          # نستخدم rtmp المباشر لتجاوز مشاكل الأمان التي تسبب فشل الاتصال
          ffmpeg -re -i "${{ github.event.inputs.video_url }}" \
          -user_agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64)" \
          -c:v libx264 -preset superfast -b:v 2500k -maxrate 2500k -bufsize 5000k \
          -pix_fmt yuv420p -g 50 -c:a aac -b:a 128k -ar 44100 \
          -f flv "rtmp://live-api-s.facebook.com:80/rtmp/FB-122183660390765411-0-Ab6BxXZD6RCKMGxdmzfqy8BT"
