name: UltraTV-Cloud-Broadcaster

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: 'https://archive.org/download/quran-4k-nature/Surah%20Al-Baqarah%204K.mp4'
        required: true

jobs:
  streaming_job:
    runs-on: ubuntu-latest
    steps:
      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Start Robust Stream
        run: |
          # إضافة ميزات لإصلاح مشاكل الاتصال مع فيسبوك
          ffmpeg -re -i "${{ github.event.inputs.video_url }}" \
          -c:v libx264 -preset superfast -b:v 2500k -maxrate 2500k -bufsize 5000k \
          -pix_fmt yuv420p -g 50 -c:a aac -b:a 128k -ar 44100 \
          -f flv -flvflags no_duration_filesize \
          -rtmp_tcurl "rtmps://live-api-s.facebook.com:443/rtmp/" \
          "rtmps://live-api-s.facebook.com:443/rtmp/FB-122183660390765411-0-Ab6BxXZD6RCKMGxdmzfqy8BT"
